services:
  gateway:
    image: hmunoz79/apigateway:1.5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9500:9500"
    environment:
      SPRING_SERVER_PORT: 9500
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://carritos-app:8081
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: carrito-service
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path=/carritos/**
    depends_on:
      - carritos-app

  carritos-app:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports: ["8081:8081"]
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://carritos-db:5432/carritos_db
      SPRING_DATASOURCE_USERNAME: user_carritos
      SPRING_DATASOURCE_PASSWORD: pass_carritos
      PELICULAS_BASE_URL: http://host.docker.internal:8080
    depends_on:
      - carritos-db

  carritos-db:
    image: postgres:13-alpine
    container_name: carritos-db-container
    environment:
      POSTGRES_DB: carritos_db
      POSTGRES_USER: user_carritos
      POSTGRES_PASSWORD: pass_carritos
    volumes:
      - carritos-data:/var/lib/postgresql/data

volumes:
  carritos-data:
