# ===============================
# Configuracion de aplicacion
# ===============================
server.port=8080
spring.application.name=carrito-service

# ===============================
# Configuracion de Base de Datos
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/carrito_db
spring.datasource.username=user_carritos
spring.datasource.password=pass_carritos
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# RabbitMQ
# ===============================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# ===============================
# Swagger/OpenAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.unrn.controller
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
springdoc.model-and-view-allowed=true
springdoc.show-actuator=false
springdoc.use-management-port=false
springdoc.paths-to-exclude=/error