# ===============================
# Configuracion de aplicacion
# ===============================
server.port=8080
spring.application.name=carrito-service

# ===============================
# Configuracion de Base de Datos
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/carritos_db
spring.datasource.username=user_carritos
spring.datasource.password=pass_carritos
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# RabbitMQ Connection Configuration
# ===============================
spring.rabbitmq.host=rabbitmq             # Use the Docker Compose service name
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===============================
# Consumer Topology Configuration
# ===============================
# Name of the shared Exchange defined by the Producer
rabbitmq.event.exchange.name=pelicula_exchange

# Name of the Queue unique to the Carrito-Backend
rabbitmq.event.consumer.queue.name=carrito_pelicula_queue

# The Binding Key uses a wildcard (*) to subscribe to all actions 
rabbitmq.event.movie.routing.key=pelicula.evento

# Enable Spring Retry for automatic reattempts on failure
spring.main.allow-bean-definition-overriding=true
spring.retry.enabled=true

# URL base del servicio de películas
peliculas.base-url=${PELICULAS_BASE_URL:http://localhost:8080}